In [55]:
import pandas as pd

In [56]:
import os

In [57]:
os.getcwd()

'C:\\Users\\chari'

In [58]:
print(os.getcwd())

C:\Users\chari

In [63]:
df = pd.read_csv(r'C:\Users\chari\Downloads\USD-INR Exchange Rate Analysis Project/Crude oil price.csv')

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 965 entries, 0 to 964
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    965 non-null    object
 1   Value   965 non-null    float64
dtypes: float64(1), object(1)
memory usage: 15.2+ KB

In [65]:
df.shape

(965, 2)

In [69]:
df.describe()

            Value
count  965.000000
mean    28.930363
std     29.881614
min      1.170000
25%      3.070000
50%     18.880000
75%     44.830000
max    139.960000

In [70]:
df1 = pd.read_csv(r'C:\Users\chari\Downloads\USD-INR Exchange Rate Analysis Project/Download Data - CURRENCY_US_XTUP_USDINR (1).csv')

In [71]:
df1

           Date   Open   High    Low  Close
0    05/19/2026  96.26  97.17  96.26  97.15
1    05/18/2026  96.03  96.62  95.89  96.27
2    05/15/2026  95.70  96.14  95.54  95.99
3    05/14/2026  95.68  95.96  95.54  95.75
4    05/13/2026  95.64  95.88  95.47  95.69
..          ...    ...    ...    ...    ...
256  05/26/2025  85.08  85.20  84.83  85.12
257  05/23/2025  85.97  86.01  85.08  85.08
258  05/22/2025  85.60  86.10  85.52  85.97
259  05/21/2025  85.55  85.70  85.47  85.60
260  05/20/2025  85.36  85.66  85.35  85.55

[261 rows x 5 columns]

In [72]:
df1.shape

(261, 5)

In [73]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    261 non-null    object
 1   Open    261 non-null    float64
 2   High    261 non-null    float64
 3   Low     261 non-null    float64
 4   Close   261 non-null    float64
dtypes: float64(4), object(1)
memory usage: 10.3+ KB

In [75]:
df2 = pd.read_csv(r'C:\Users\chari\Downloads\USD-INR Exchange Rate Analysis Project/Repo rate.csv')

In [76]:
df2

           Date Value
0    03-01-1968    5%
1    06-01-1968    5%
2    09-01-1968    5%
3    12-01-1968    5%
4    03-01-1969    5%
..          ...   ...
219  12-01-2022    6%
220  03-01-2023    7%
221  06-01-2023    7%
222  09-01-2023    7%
223  12-01-2023    7%

[224 rows x 2 columns]

In [77]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    224 non-null    object
 1   Value   224 non-null    object
dtypes: object(2)
memory usage: 3.6+ KB

In [78]:
df3 = pd.read_csv(r'C:\Users\chari\Downloads\USD-INR Exchange Rate Analysis Project/Gold price.csv')

In [79]:
df3

           Date    Price
0    01-05-2016  1260.95
1    01-06-2016  1276.40
2    01-07-2016  1336.66
3    01-08-2016  1340.17
4    01-09-2016  1326.61
..          ...      ...
114  01-11-2025  4087.19
115  01-12-2025  4309.23
116  01-01-2026  4752.75
117  01-02-2026  5019.97
118  01-03-2026  4855.54

[119 rows x 2 columns]

In [80]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    119 non-null    object
 1   Price   119 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.0+ KB

In [81]:
df.head()

         Date  Value
0  01-01-1946   1.17
1  02-01-1946   1.17
2  03-01-1946   1.17
3  04-01-1946   1.27
4  05-01-1946   1.27

In [82]:
df1.head()

         Date   Open   High    Low  Close
0  05/19/2026  96.26  97.17  96.26  97.15
1  05/18/2026  96.03  96.62  95.89  96.27
2  05/15/2026  95.70  96.14  95.54  95.99
3  05/14/2026  95.68  95.96  95.54  95.75
4  05/13/2026  95.64  95.88  95.47  95.69

In [83]:
df2.head()

         Date Value
0  03-01-1968    5%
1  06-01-1968    5%
2  09-01-1968    5%
3  12-01-1968    5%
4  03-01-1969    5%

In [84]:
df3.head()

         Date    Price
0  01-05-2016  1260.95
1  01-06-2016  1276.40
2  01-07-2016  1336.66
3  01-08-2016  1340.17
4  01-09-2016  1326.61

In [85]:
df.shape

(965, 2)

In [86]:
df = pd.read_csv(r'C:\Users\chari\Downloads\USD-INR Exchange Rate Analysis Project/Crude oil price.csv')

In [87]:
df.shape

(121, 2)

In [88]:
df1 = pd.read_csv(r'C:\Users\chari\Downloads\USD-INR Exchange Rate Analysis Project/Download Data - CURRENCY_US_XTUP_USDINR.csv')

In [89]:
df1.shape

(262, 5)

In [90]:
df1 = pd.read_csv(r'C:\Users\chari\Downloads\USD-INR Exchange Rate Analysis Project/USDINR.csv')

In [91]:
df1.shape

(2467, 5)

In [93]:
df2 = pd.read_csv(r'C:\Users\chari\Downloads\USD-INR Exchange Rate Analysis Project/Repo rate.csv')
df2.shape

(224, 2)

In [94]:
df2 = pd.read_csv(r'C:\Users\chari\Downloads\USD-INR Exchange Rate Analysis Project/rbi_repo_rate.csv')
df2.shape

(3606, 2)

In [95]:
import sqlalchemy as sal

In [97]:
engine = sal.create_engine('mysql+pymysql://root:123456@localhost:3306/exchange_rate')
conn=engine.connect()

In [102]:
df.to_sql(name = 'crude_oil_price', con=conn, index= False)

121

In [107]:
df1.to_sql(name = 'usdinr', con=conn, index= False, if_exists = 'replace')

2467

In [110]:
df2.to_sql(name = 'repo_rate', con=conn, index= False, if_exists = 'replace')

3606

In [111]:
df3.to_sql(name = 'gold_price', con=conn, index= False, if_exists = 'replace')

119

In [122]:
query1 = """
Select  date_format(str_to_date(Date, '%%m-%%d-%%Y'), '%%M %%d,%%Y') as formated_date, value
FROM crude_oil_price
"""
df = pd.read_sql(query1, engine)
df

         formated_date   value
0          May 01,2016   49.10
1         June 01,2016   48.27
2         July 01,2016   41.54
3       August 01,2016   44.68
4    September 01,2016   47.72
..                 ...     ...
116    January 01,2026   64.50
117   February 01,2026   66.96
118      March 01,2026  102.86
119      April 01,2026  108.64
120        May 01,2026  101.56

[121 rows x 2 columns]

In [123]:
df.to_csv(r"C:\Users\chari\Downloads/cleaned_crude_oil_price.csv", index= False)

In [124]:
query2 = """
Select  date_format(str_to_date(Date, '%%d-%%m-%%Y'), '%%M %%d,%%Y') as formated_date, open, high, low, close
FROM usdinr
"""
df1 = pd.read_sql(query2, engine)
df1

     formated_date     open     high      low    close
0      May 02,2016  66.3200  66.4150  66.3200  66.3900
1      May 03,2016  66.2850  66.3800  66.2300  66.3725
2      May 04,2016  66.5950  66.6600  66.4950  66.6350
3      May 05,2016  66.5650  66.6050  66.4525  66.4900
4      May 06,2016  66.5650  66.6200  66.5325  66.5800
...            ...      ...      ...      ...      ...
2462   May 13,2026  95.6905  95.8015  95.5855  95.7125
2463   May 14,2026  95.8265  95.9625  95.6325  95.7695
2464   May 15,2026  95.9425  96.1425  95.8805  95.9695
2465   May 18,2026  96.2825  96.3905  96.2525  96.3555
2466   May 19,2026  96.3275  96.6175  96.2755  96.5375

[2467 rows x 5 columns]

In [127]:
df1.to_csv(r"C:\Users\chari\Downloads/cleaned_usdinr.csv", index= False)

In [126]:
query3 = """
Select  date_format(str_to_date(Date, '%%d-%%m-%%Y'), '%%M %%d,%%Y') as formated_date, repo_rate
FROM repo_rate
"""
df2 = pd.read_sql(query3, engine)
df2

         formated_date  repo_rate
0      January 05,2016       6.25
1      January 06,2016       6.25
2      January 07,2016       6.25
3      January 08,2016       6.25
4      January 09,2016       6.25
...                ...        ...
3601  November 14,2025       5.85
3602  November 15,2025       5.85
3603  November 16,2025       5.85
3604  November 17,2025       5.85
3605   January 01,2026       5.25

[3606 rows x 2 columns]

In [128]:
df2.to_csv(r"C:\Users\chari\Downloads/cleaned_repo_rate.csv", index= False)

In [125]:
query4 = """
Select  date_format(str_to_date(Date, '%%d-%%m-%%Y'), '%%M %%d,%%Y') as formated_date, price
FROM gold_price
"""
df3 = pd.read_sql(query4, engine)
df3

         formated_date    price
0          May 01,2016  1260.95
1         June 01,2016  1276.40
2         July 01,2016  1336.66
3       August 01,2016  1340.17
4    September 01,2016  1326.61
..                 ...      ...
114   November 01,2025  4087.19
115   December 01,2025  4309.23
116    January 01,2026  4752.75
117   February 01,2026  5019.97
118      March 01,2026  4855.54

[119 rows x 2 columns]

In [129]:
df3.to_csv(r"C:\Users\chari\Downloads/cleaned_gold_price.csv", index= False)